//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mesaj.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MesajEkle", ReplyAction="http://tempuri.org/IService1/MesajEkleResponse")]
        string MesajEkle(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MesajEkle", ReplyAction="http://tempuri.org/IService1/MesajEkleResponse")]
        System.Threading.Tasks.Task<string> MesajEkleAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MesajGetir", ReplyAction="http://tempuri.org/IService1/MesajGetirResponse")]
        string MesajGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MesajGetir", ReplyAction="http://tempuri.org/IService1/MesajGetirResponse")]
        System.Threading.Tasks.Task<string> MesajGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MesajlarıiSil", ReplyAction="http://tempuri.org/IService1/MesajlarıiSilResponse")]
        void MesajlarıiSil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MesajlarıiSil", ReplyAction="http://tempuri.org/IService1/MesajlarıiSilResponse")]
        System.Threading.Tasks.Task MesajlarıiSilAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_Mesaj.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Mesaj.ServiceReference1.IService1>, WCF_Mesaj.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MesajEkle(string value) {
            return base.Channel.MesajEkle(value);
        }
        
        public System.Threading.Tasks.Task<string> MesajEkleAsync(string value) {
            return base.Channel.MesajEkleAsync(value);
        }
        
        public string MesajGetir() {
            return base.Channel.MesajGetir();
        }
        
        public System.Threading.Tasks.Task<string> MesajGetirAsync() {
            return base.Channel.MesajGetirAsync();
        }
        
        public void MesajlarıiSil() {
            base.Channel.MesajlarıiSil();
        }
        
        public System.Threading.Tasks.Task MesajlarıiSilAsync() {
            return base.Channel.MesajlarıiSilAsync();
        }
    }
}
